### ISSUE TITLE
Firefox crashes

### ISSUE THREAD

**Issue by nerdyCamel** [mrfixit2001/debian_desktop#13]
On a Pinebook Pro, Firefox crashes after a few seconds. I tried Youtube first. The resolution was set to 1080p. I played around with the playback speed (1x to 1.75x). It also crashes on other pages. I tried pine64.com, debian.org and mozilla.org. The behaviour ist reproducible. My system is up to date. The CPU governor was set to 'on demand'.

**Comment by francistheodorecatte** [comment]
I can confirm random Firefox crashes too. Seems to be related to hardware accelerated rendering. Here's an example crash log, where I triggered the crash via a full-screen youtube video: https://crash-stats.mozilla.com/report/index/d3b7139e-5a29-4859-bec0-360560191101

This seems to be a long standing bug that affects mostly Firefox for Android afaik. Does Android use the GL4ES wrapper too?

**Comment by matthewadie** [comment]
I get the random crashes as well...  When I launch it from the command line it gives me the following when it crashes:

Debian-Desktop:~$ firefox
ExceptionHandler::GenerateDump cloned child 5526
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
Exiting due to channel error.
Exiting due to channel error.
[Child 5285, Chrome_ChildThread] WARNING: pipe error (3): Connection reset by peer: file /home/pi/firefox-65.0+build2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 349
Exiting due to channel error.
Bus error

It also crashes when I launch it in safe-mode.

Matthew

**Comment by iav** [comment]
Not sure it's related, but for me fitefox hangs on start. Task manager shows 2 firefox processes, one of them wait on futex. If I kill that process — firefox starts and work.
But youtube plays videos without sound. Other sites plays videos with sound.
Chromium plays youtube video with sound.

Update script was run today.

**Comment by jsfrederick** [comment]
I am having this issue as well.  Sometimes it crashes on start up, other times it'll start up and run for s while before it crashes.  Trying to run down a pattern or common issue.  Will post here if I can get more details.

**Comment by SatnSpwn** [comment]
I've had the same issue. I downloaded [this](http://ports.ubuntu.com/pool/main/f/firefox/firefox_70.0.1+build1-0ubuntu0.16.04.1_armhf.deb) and installed it.  I've been using it for 1 1/2 - 2 days with no crashes. I have not checked youtube or video yet

The version of firefox in this image is from ubuntu. You have to download and install it manually to update it.

**Comment by mrfixit2001** [comment]
I have pushed a new debian desktop update that includes the newest version of firefox, which thus far is testing very stable :)
